apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: redis
    app: demo-voting-app
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
  selector: # add labels of pod or deployments
    name: redis-app-pod
    app: demo-voting-app
