apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    name: result-app-service
    app: demo-voting-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30005
  selector: # add labels of pod 
   name: result-app-pod
   app: demo-voting-app